pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                sh 'cd hello-devops-revision && mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'cd hello-devops-revision && mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'cd hello-devops-revision && mvn package'
            }
        }
    }
}
